version: '3'
services:
  php:
    image: php:7.4-fpm
    volumes:
      - './:/var/www/html'

  nginx:
    hostname: asem.local
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    environment:
      - NGINX_HOST=asem.local
      - NGINX_PORT=80

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
